     Numpy:

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np

In [3]:
## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)  
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size)  
print("Data type:", arr.dtype)  
print("Item size (in bytes):", arr.itemsize)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
arr[1:,2:]


array([[ 7,  8],
       [11, 12]])

In [19]:
## Modify array elements
arr[0,0]=100
arr[1,3]=23
print(arr)

[[100   2   3   4]
 [  5   6   7  23]
 [  9  10  11  12]]


In [20]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [23]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [8]:
import numpy as np

In [9]:
 # higher Dimentional arrays
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


     intial placeholder in numpy array:

   -in some cases we want to intiate array with certain values

In [ ]:
 # create numpy array with all the values are zero
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
 # create numpy array with all the values are one
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
import numpy as np

In [16]:
# creating identity matrix- all the diogonal element will be one and rest all the values 
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


     Analysing numpy array:

In [4]:
import numpy as np

In [ ]:
 # shape
x=np.random.randint(10,99,(4,5))
print(x)
print("Shape of the array:\n ",x.shape)

[[19 71 81 40 87]
 [15 74 68 49 51]
 [51 84 98 50 90]
 [51 72 77 16 83]]
Shape of the array:
  (4, 5)


In [ ]:
 # dimenation of the array
x.ndim

2

In [ ]:
 # number of the element present in the array
x.size

20

In [ ]:
 #checking the datatype of the element in the array
x.dtype

dtype('int32')

In [3]:
import numpy as np

In [4]:
myarr=np.random.randint(10,20,10)
print(myarr)

[19 18 17 14 15 10 11 15 19 13]


In [ ]:
myarr.max()

np.int32(19)

In [ ]:
 # index location of max value
myarr.argmax()

np.int64(4)

In [5]:
myarr.min()

np.int32(10)

In [ ]:
 #index location of min value
myarr.argmin()

np.int64(5)

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b            # Element-wise addition


array([5, 7, 9])

In [5]:
a - b            # Element-wise subtraction

array([-3, -3, -3])

In [6]:
# Element-wise multiplication
a*b

array([ 4, 10, 18])

In [7]:
# Element-wise division
a/b

array([0.25, 0.4 , 0.5 ])

In [8]:
# Dot product
np.dot(a, b)

np.int64(32)

In [9]:
arr = np.array([10, 20, 30, 40, 50])

arr[0]           # First element

np.int64(10)

In [10]:
# Last element
arr[-1]  

np.int64(50)

In [11]:
# Slice from index 1 to 3
arr[1:4] 

array([20, 30, 40])

In [12]:
 # First 3 elements
arr[:3] 

array([10, 20, 30])

In [13]:
# Sum of elements
np.sum(arr) 

np.int64(150)

In [14]:
# Mean of elements
np.mean(arr)  

np.float64(30.0)

In [15]:
# Maximum value
np.max(arr) 

np.int64(50)

In [16]:
 # Minimum value
np.min(arr)  

np.int64(10)

In [17]:
# Sort array
np.sort(arr)

array([10, 20, 30, 40, 50])

In [18]:
# Unique values
np.unique(arr)

array([10, 20, 30, 40, 50])

In [19]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([11,22,33,44,55])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
data = np.array([23,43,45,65,23,14,56,28,19,20])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 33.6
Median: 25.5
Standard Deviation: 16.566230711903053
Variance: 274.43999999999994


In [22]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)

[[14 12 17]
 [18 19 17]
 [14 14 15]]
[[29 24 22]
 [22 23 24]
 [22 20 25]]


In [ ]:
print(a+b)   
#==> same result could be obtained by np.add(a,b)

[[43 36 39]
 [40 42 41]
 [36 34 40]]


In [24]:
print(a-b)    
#==> same result could be obtained by np.substract(a,b)

[[-15 -12  -5]
 [ -4  -4  -7]
 [ -8  -6 -10]]


In [25]:
print(a/b)    
#==> same result could be obtained by np.division(a,b)

[[0.48275862 0.5        0.77272727]
 [0.81818182 0.82608696 0.70833333]
 [0.63636364 0.7        0.6       ]]


In [26]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr/arr

C:\Users\anany\AppData\Local\Temp\ipykernel_10580\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [29]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [30]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr.min()

np.int64(0)

In [33]:
arr.max()

np.int64(10)

In [ ]:
arr.var()

np.float64(10.0)

In [36]:
arr.mean()

np.float64(5.0)

In [37]:
arr.std()

np.float64(3.1622776601683795)

       Array Manipulation:

In [38]:
 # transpose
array1=np.random.randint(10,20,(2,3))
print(array1)
array1.shape

[[12 17 14]
 [11 16 14]]


(2, 3)

In [39]:
trans=np.transpose(array1)
print(trans)
trans.shape

[[12 11]
 [17 16]
 [14 14]]


(3, 2)