     Numpy:

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/12.8 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.8 MB 2.3 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.8 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.8 MB 2.7 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.8 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.8 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.6 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.8 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.8 MB 2.5 MB/s eta 0:00:03
   ----------


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)  
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size)  
print("Data type:", arr.dtype)  
print("Item size (in bytes):", arr.itemsize)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
arr[1:,2:]


array([[ 7,  8],
       [11, 12]])

In [19]:
## Modify array elements
arr[0,0]=100
arr[1,3]=23
print(arr)

[[100   2   3   4]
 [  5   6   7  23]
 [  9  10  11  12]]


In [20]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [23]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [8]:
import numpy as np

In [ ]:
 # higher Dimentional arrays
 arr = np.array([1, 2, 3, 4], ndmin=5)
 print(arr)
 print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


     intial placeholder in numpy array:

   -in some cases we want to intiate array with certain values

In [10]:
 # create numpy array with all the values are zero
 x=np.zeros((4,5))
 print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
 # create numpy array with all the values are one
 x=np.ones((4,5))
 print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
import numpy as np

In [16]:
# creating identity matrix- all the diogonal element will be one and rest all the values 
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


     Analysing numpy array:

In [17]:
 # shape
 x=np.random.randint(10,99,(4,5))
 print(x)
 print("Shape of the array:\n ",x.shape)

[[95 23 82 44 24]
 [19 73 39 73 93]
 [68 67 28 51 59]
 [50 39 16 23 52]]
Shape of the array:
  (4, 5)


In [ ]:
 # dimenation of the array
 x.ndim

2

In [22]:
 # number of the element present in the array
 x.size

20

In [23]:
 #checking the datatype of the element in the array
 x.dtype

dtype('int32')

In [24]:
 myarr=np.random.randint(10,20,10)
 print(myarr)

[16 14 13 13 19 19 11 15 12 15]


In [25]:
 myarr.max()

np.int32(19)

In [26]:
 # index location of max value
 myarr.argmax()

np.int64(4)

In [27]:
 myarr.min()

np.int32(11)

In [28]:
 #index location of min value
 myarr.argmin()

np.int64(6)